<IncrementalWidget>:
    orientation: 'vertical'
    padding: ['10dp', '10dp', '10dp', '10dp']

    BoxLayout:
        size_hint_y: None
        height: '45dp'
        padding: [0, 0, 0, '10dp']
        Label:
            text: 'Nom du sujet:'
            font_size: '18sp'
            size_hint_x: None
            width: '130dp'
        TextInput:
            id: subject_name_input
            text: 'sujet'
            font_size: '18sp'
            multiline: False

    #---- PARTIE TABLEAU DE SAISIE ----#
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: 0.3

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: '45dp'
            spacing: '6dp'
                        
            Button:
                text: 'Ajouter un point'
                font_size: '18sp'
                on_press: root.add_point()
            
            Button:
                text: "Charger profil"
                font_size: '18sp'
                on_release: root.load_profile()
            Button:
                text: "Sauvegarder profil"
                font_size: '18sp'
                on_release: root.save_profile()

        GridLayout:
            cols: 5
            size_hint_y: None
            height: "35dp"
            row_default_height: "35dp"
            row_force_default: True
            padding: [0, '4dp']
            spacing: ['4dp', '4dp']
            Label:
                text: 'Temps [s]'
                font_size: '18sp'
            Label:
                text: 'Inclinaison [°]'
                font_size: '18sp'
            Label:
                text: 'Vitesse [km/h]'
                font_size: '18sp'
            Label:
                text: 'Vitesse Asc. [m/h]'
                font_size: '18sp'
            Label:
                text: ''
                size_hint_x: None
                width: '110dp'

        BoxLayout:         # conteneur pour ScrollView
            orientation: 'vertical'
            size_hint_y: 1   # prend tout l'espace restant dans la zone 0.3

            ScrollView:
                do_scroll_x: False
                do_scroll_y: True
                bar_width: '10dp'
                size_hint_y: 1

                GridLayout:
                    id: points_grid
                    cols: 5
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: "35dp"
                    row_force_default: True
                    padding: [0, '4dp']
                    spacing: ['4dp', '4dp']

    #---- ESPACE DE SEPARATION ----#
    BoxLayout:
        size_hint_y: None
        height: '10dp'

    #---- PARTIE GRAPHIQUE ----#
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: 0.4

        BoxLayout:
            size_hint_y: None
            height: '45dp'
            spacing: '6dp'
            Label:
                text: 'Abscisse:'
                font_size: '18sp'
                size_hint_x: None
                width: '110dp'
            ToggleButton:
                text: 'Inclinaison'
                font_size: '18sp'
                group: 'graph_axis'
                state: 'down'
                allow_no_selection: False
                on_press: root.set_graph_variable('incl')
            ToggleButton:
                text: 'Vitesse'
                font_size: '18sp'
                group: 'graph_axis'
                allow_no_selection: False
                on_press: root.set_graph_variable('speed')
            ToggleButton:
                text: 'Vitesse Asc.'
                font_size: '18sp'
                group: 'graph_axis'
                allow_no_selection: False
                on_press: root.set_graph_variable('asc')

        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                id: graph_view
            BoxLayout:
                size_hint_x: None
                width: '60dp'
                orientation: 'vertical'
                Label:
                    text: 'Zoom'
                    font_size: '16sp'
                    size_hint_y: None
                    height: '25dp'
                Slider:
                    id: zoom_slider
                    orientation: 'vertical'
                    min: 1
                    max: 20
                    value: root.zoom
                    step: 1
                    on_value: root.update_graph_zoom(self.value)

    #---- ESPACE DE SEPARATION ----#
    BoxLayout:
        size_hint_y: None
        height: '10dp'

    #---- PARTIE EVENEMENTS ----#
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: 0.3

        BoxLayout:
            size_hint_y: None
            height: "45dp"
            Button:
                text: "Ajouter un événement"
                font_size: '18sp'
                on_release: root.add_event()
   
        GridLayout:
            cols: 7
            size_hint_y: None
            height: "35dp"
            row_default_height: "35dp"
            row_force_default: True
            padding: [0, '4dp']
            spacing: ['4dp', '4dp']

            # En-têtes
            Label: 
                text: "Temps [s]"
                font_size: '18sp'
            Label: 
                text: "Vitesse SP"
                font_size: '18sp'
            Label:
                text: "Vitesse PV"
                font_size: '18sp'
            Label: 
                text: "Inclinaison SP"
                font_size: '18sp'
            Label:
                text: "Inclinaison PV"
                font_size: '18sp'
            Label: 
                text: "Vitesse Asc. SP"
                font_size: '18sp'
            Label:
                text: "Vitesse Asc. PV"
                font_size: '18sp'

        BoxLayout:         # conteneur pour ScrollView
            orientation: 'vertical'
            size_hint_y: 1   # prend tout l'espace restant dans la zone 0.3
            ScrollView:
                do_scroll_x: False
                do_scroll_y: True
                bar_width: '10dp'
                size_hint_y: 1
                GridLayout:
                    id: events_grid
                    cols: 7
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: "35dp"
                    row_force_default: True
                    padding: [0, '4dp']
                    spacing: ['4dp', '4dp']


        
