#CONFIGURATION FILE TO CONFIGURE LE_MUR

#REVOLUTION PI 
CYCLETIME_MS : 10       #cycle time in ms

#MECAHNICAL CHARATERISTICS
BELT_LENGTH_MM : 2400   #distance between wheel and pivot
Z_MOTOR : 26            # tooth on motor side
Z_BELT : 64             # tooth on belt side
RADIUS_CYL_MM : 93      # Raduis of belt cynlinder on motor side 186/2

#LIFT MOTOR PARAMETERS
LIFT_FREQ_HZ : 50       #max frequency during travel
LIFT_HZ2mV  : 100        #conversion factor to output frequency to mV
LIFT_ACC_S : 6.34       #acc time from 0Hz to 50Hz

#CALIBRATION FACTOR TO CONVERT TILT OUTPUT in mV to DEGREES
CAL_TILT_A : -0.071732393 # Slope
CAL_TILT_B : 268.9148431  ## Offset